### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by dziemba** [salesking/king_dtaus#15]
We would like to use the feature in this commit https://github.com/salesking/king_dtaus/commit/b68a3a32fdfce29a53ebf1694b93fbd828e10c2c but there has been no gem release yet where it is included. Can you release a new gem version soon?

**Comment by dziemba** [comment]
Apparently not.

**Comment by schorsch** [comment]
i can bump a new version; do you still need it?

**Comment by dziemba** [comment]
Thanks for the quick reply. No, we already forked the repo and made some custom changes. I was just going through my open Issues.

**Comment by schorsch** [comment]
Ok, just let me know about some reasonable changes and i will pull & bump

2015-07-09 11:25 GMT+02:00 Niko Dziemba notifications@github.com:

**Comment by dziemba** [comment]
This is currently the only patch we added: https://github.com/salesking/king_dtaus/pull/16

I am not sure if you want to merge this, though.
